### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Robin1suen** [thegedge/StereoReconstruction#1]
Hello，is the code for point cloud rendering complete?
We have a project that requires point rendering, hope we can use this part of the code.

**Comment by thegedge** [comment]
Hey, @Robin1suen.

This code is over a decade old, and was used for research, so know that I wouldn't consider it useful outside of a research context. Also note that it's GPL-licensed, so if you don't want to license your own code as GPL, I would recommend writing your own point renderer (or finding a better one).

All that being said, if I recall correctly, the point rendering code (with a splat shader) was definitely working in 2011, but may not work in more modern OpenGL. The point render was incredibly basic, and I doubt it would hold up against more modern point renderers.

Cheers 👋
